#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          resque
# Required-Start:    $networking
# Required-Stop:     $networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the resque daemon
# Description:       starts the resque daemon using start-stop-daemon
### END INIT INFO
# Install in /etc/init.d

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/var/www/dev/vendor/ebernhardson/php-resque-pool/bin/resque-pool
NAME=resque
DESC="Resque"
CONFIG_FILE="/etc/resque/pool.yml"

#test -f $DAEMON || exit 0

case "$1" in

  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --name $NAME -v -b -x $DAEMON \
           -p /tmp/$NAME.pid -- --config $CONFIG_FILE 1>>/var/log/$NAME.log >> /var/log/$NAME.error.log

    echo "$NAME."
    ;;

  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop -x $DAEMON -p /tmp/$NAME.pid -q
    echo "$NAME."
    ;;

  reload)
    echo -n "Reload $DESC: "
    killall mono --signal SIGHUP
        #start-stop-daemon --stop --signal 1 -x $DAEMON -p /tmp/$NAME.pid -q
    echo "$NAME."
    ;;

  restart|force-reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon --stop -x $DAEMON -p /tmp/$NAME.pid -q
    sleep 1
    start-stop-daemon --start --name $name -v -b -x $DAEMON \
           -p /tmp/$NAME.pid 1>>/var/log/$NAME.log >> /var/log/$NAME.log2
    echo "$NAME."
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0

#end script